### ISSUE TITLE
Screen not initializing after installing Release branch

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/RoboLCD_Release#1]
After uninstalling RoboLCD and installing RoboLCD-Release, the screen no longer initializes.  This is the output I'm getting from the logs:

```
2016-08-10 00:03:28,183 - octoprint.plugin.core - INFO - 14 plugin(s) registered with the system:
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.15-py2.7.egg/octoprint/plugins/announcements
|  Cost Plugin (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_cost
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.15-py2.7.egg/octoprint/plugins/cura
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.15-py2.7.egg/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Firmware Updater (0.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_firmwareupdater
|  Netconnectd Client (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_netconnectd
|  OctoPrint-Mixpanel (0.1.0) = /home/pi/OctoPrint-Mixpanel/octoprint_mixpanel
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.15-py2.7.egg/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_portlister
|  Printer Stats (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stats
|  RoboLCD (0.2.1) = /home/pi/RoboLCD_Release/RoboLCD
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.15-py2.7.egg/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.15-py2.7.egg/octoprint/plugins/virtual_printer
2016-08-10 00:03:28,185 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2016-08-10 00:03:28,255 - octoprint.filemanager - INFO - Added 1 items from storage type "local" to analysis queue
2016-08-10 00:03:28,258 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2016-08-10 00:03:28,280 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2016-08-10 00:03:28,809 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2016-08-10 00:03:28,853 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on happy-einstein for _http._tcp
2016-08-10 00:03:28,871 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on happy-einstein for _octoprint._tcp
2016-08-10 00:03:28,875 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2016-08-10 00:03:28,877 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on happy-einstein for SSDP
2016-08-10 00:03:28,879 - octoprint.plugins.portlister - INFO - Port Lister () {}
2016-08-10 00:03:28,897 - octoprint.plugins.stats - INFO - Printer Stats
2016-08-10 00:03:29,002 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.0.143
2016-08-10 00:03:29,373 - octoprint.plugins.mixpanel - INFO - Hello World! I want to log events!
2016-08-10 00:03:29,378 - octoprint.plugins.RoboLCD - INFO - RoboLCD Starting up
2016-08-10 00:03:29,381 - octoprint.plugins.RoboLCD - INFO - Rendering screen... 
2016-08-10 00:03:29,469 - kivy - INFO - Logger: Record log in /home/pi/.kivy/logs/kivy_16-08-10_0.txt
2016-08-10 00:03:29,468 - kivy - INFO - Kivy: v1.9.2-dev0
2016-08-10 00:03:29,472 - kivy - INFO - Python: v2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2]
2016-08-10 00:03:29,774 - kivy - INFO - Factory: 193 symbols loaded
2016-08-10 00:03:31,252 - kivy - INFO - Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
2016-08-10 00:03:31,351 - kivy - INFO - Text: Provider: sdl2
2016-08-10 00:03:31,850 - kivy - INFO - Window: Provider: egl_rpi
2016-08-10 00:03:31,994 - kivy - INFO - GL: OpenGL version <OpenGL ES 2.0>
2016-08-10 00:03:31,996 - kivy - INFO - GL: OpenGL vendor <Broadcom>
2016-08-10 00:03:31,998 - kivy - INFO - GL: OpenGL renderer <VideoCore IV HW>
2016-08-10 00:03:32,000 - kivy - INFO - GL: OpenGL parsed version: 2, 0
2016-08-10 00:03:32,001 - kivy - INFO - GL: Shading version <OpenGL ES GLSL ES 1.00>
2016-08-10 00:03:32,003 - kivy - INFO - GL: Texture max size <2048>
2016-08-10 00:03:32,005 - kivy - INFO - GL: Texture max units <8>
2016-08-10 00:03:32,008 - kivy - INFO - Shader: fragment shader: <Compiled>
2016-08-10 00:03:32,010 - kivy - INFO - Shader: vertex shader: <Compiled>
2016-08-10 00:03:32,040 - kivy - INFO - Window: virtual keyboard allowed, single mode, docked
2016-08-10 00:03:32,332 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.0.203/'}
2016-08-10 00:03:32,489 - kivy - INFO - GL: NPOT texture support is available
2016-08-10 00:03:32,645 - kivy - INFO - Screen Type: lcd_mini
2016-08-10 00:03:32,681 - kivy - INFO - OSC: using <multiprocessing> for socket
2016-08-10 00:03:32,697 - kivy - ERROR - Input: MTDev is not supported by your version of linux
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/input/providers/__init__.py", line 40, in <module>
    import kivy.input.providers.mtdev
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/input/providers/mtdev.py", line 75, in <module>
    from kivy.lib.mtdev import Device, \
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/lib/mtdev.py", line 28, in <module>
    libmtdev = cdll.LoadLibrary('libmtdev.so.1')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmtdev.so.1: cannot open shared object file: No such file or directory
2016-08-10 00:03:32,752 - kivy - INFO - ProbeSysfs: device match: /dev/input/event0
2016-08-10 00:03:32,756 - kivy - INFO - HIDInput: Read event from </dev/input/event0>
2016-08-10 00:03:32,760 - kivy - INFO - HIDInput: Set custom rotation to 270
2016-08-10 00:03:32,762 - kivy - INFO - HIDInput: Set custom invert_y to 1
2016-08-10 00:03:32,763 - kivy - INFO - Base: Start application main loop
2016-08-10 00:03:32,766 - kivy - INFO - HIDMotionEvent: using <ADS7846 Touchscreen>
2016-08-10 00:03:32,773 - kivy - INFO - HIDMotionEvent: <ADS7846 Touchscreen> range ABS X position is 0 - 4095
2016-08-10 00:03:32,798 - kivy - INFO - HIDMotionEvent: <ADS7846 Touchscreen> range ABS Y position is 0 - 4095
2016-08-10 00:03:32,808 - kivy - INFO - HIDMotionEvent: <ADS7846 Touchscreen> range ABS pressure is 0 - 65535
2016-08-10 00:03:32,846 - kivy - INFO - Status: File List Updated
2016-08-10 00:03:32,851 - kivy - INFO - Base: Leaving application in progress...
2016-08-10 00:03:32,860 - octoprint.plugins.firmwareupdater - INFO - Retrieving current firmware version from printer...
2016-08-10 00:03:32,865 - kivy - WARNING - stderr: Unhandled exception in thread started by <function start at 0x74eb8570>
2016-08-10 00:03:32,869 - octoprint.server - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/pi/RoboLCD_Release/RoboLCD/lcd/__init__.py", line 232, in start
    RoboLcdApp().run()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 89, in mainloop
    self._mainloop()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 84, in _mainloop
    EventLoop.idle()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/clock.py", line 521, in tick
    self._process_events()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/clock.py", line 653, in _process_events
    event.tick(self._last_tick, remove)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/kivy/clock.py", line 412, in tick
    ret = callback(self._dt)
  File "/home/pi/RoboLCD_Release/RoboLCD/lcd/mainscreen.py", line 25, in update
    self.ids.files_content.update(dt)
  File "/home/pi/RoboLCD_Release/RoboLCD/lcd/files.py", line 73, in update
    b = self.create_file_button(fm, md)
  File "/home/pi/RoboLCD_Release/RoboLCD/lcd/files.py", line 51, in create_file_button
    duration = math.ceil(metadata['analysis']['estimatedPrintTime'])
KeyError: 'analysis'
2016-08-10 00:03:57,458 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.0.184/'}
2016-08-10 00:04:02,358 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://happy-einstein.local/'}
2016-08-10 00:04:02,920 - octoprint.util.pip - INFO - Found pip at /home/pi/oprint/bin/pip, version is 8.1.2
2016-08-10 00:04:03,101 - octoprint.plugins.firmwareupdater - ERROR - Unable to get printer's data
2016-08-10 00:04:03,302 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2016-08-10 00:04:07,241 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.0.121
2016-08-10 00:04:08,151 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'en', 'path': '/', 'base_url': 'http://127.0.0.1/'}
2016-08-10 00:04:13,220 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.0.124/'}
2016-08-10 00:04:18,913 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.0.103/'}
2016-08-10 00:04:18,977 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.0.175/'}
2016-08-10 00:04:23,264 - octoprint.plugins.firmwareupdater - INFO - Retrieving current firmware version from printer...
```

**Comment by AllenMcAfee** [comment]
Issue traced back to trying to estimate print time from and STL during startup.  Cannot complete this task, so it errors out.  Removed the STL I had in my library and the screen works again.

**Comment by victorevector** [comment]
Closed and moved over the development repo
